import type { LegalSection } from "@/components/legal/LegalPage";

export const DISCLAIMER_SECTIONS: LegalSection[] = [
  {
    heading: "General legal notice",
    paragraphs: [
      "This legal notice governs access to and use of the Al-Andalus Translate website (hereinafter, \"the Site\"), an online Arabic–Spanish translation service intended to support everyday communication for individuals, families, and small organizations that live with both languages in Spain, Latin America, the Maghreb, and other parts of the Arabic-speaking world.",
      "By browsing the Site, using the translator, or reading any of its informational pages, you represent that you have read and understood this document. If you do not agree with any of its provisions, we recommend that you refrain from using the service. The Site owner reserves the right to update this notice at any time; the date of the last revision appears in the page header (May 2026).",
      "The information published here is general in nature and does not constitute legal, tax, immigration, medical, or other professional advice. The Site is provided \"as is\" and on an availability basis, without implied warranties of merchantability, fitness for a particular purpose, or non-infringement of third-party rights, to the extent permitted by applicable Spanish and European law.",
      "Nothing in this notice creates a contractual relationship other than what may arise under the Terms and Conditions or the Privacy Policy. Those documents should be read together with this notice for a complete understanding of your rights and obligations as a user.",
    ],
  },
  {
    heading: "Notice regarding use of the translation tool",
    paragraphs: [
      "Al-Andalus Translate uses machine translation technology. Results are generated by statistical or neural models that predict linguistic equivalents from large text corpora; except in exceptional technical-support cases, certified human translators and sworn interpreters are not involved in normal use.",
      "Therefore, translations obtained through the Site have no legal, administrative, or official validity before courts, notaries, consulates, immigration offices, social security agencies, healthcare providers, or bodies that require documentation translated by an authorized professional under the rules of the receiving State. For contracts, academic certificates, medical reports, deeds, pleadings, or asylum and residence applications, you must use a sworn translator-interpreter or the official service required in your jurisdiction.",
      "The Site is designed for family messages, social media posts, understanding news, email drafts, orientation before an appointment with a professional, or language learning. It does not replace human review when an error could cause financial harm, affect your immigration status, alter a diagnosis, or misinterpret contractual obligations.",
      "Arabic dialects (for example Moroccan, Algerian, or Levantine darija) may be translated less reliably than Modern Standard Arabic (MSA). Likewise, regional Spanish slang, highly local expressions, or text with serious spelling errors may produce incorrect or incoherent output. You are responsible for verifying the meaning of translated text before making decisions based on it.",
      "You may not present translator output as an official document, certificate, or document signed or endorsed by the Site. Any misuse that leads third parties to mistake the origin or authority of a translation may result in access restrictions and, where appropriate, legal action.",
    ],
  },
  {
    heading: "Links to third-party sites",
    paragraphs: [
      "The Site may include links to external pages (language resources, public institutions, reference articles, analytics or advertising providers) that are not under our editorial or technical control. Inclusion of a link does not imply endorsement, association, or prior verification of the destination's content, privacy policies, or security practices.",
      "When you leave our domain, you are subject to the terms and conditions of the destination site. We recommend reading its legal notices and cookie policies before providing personal data. We do not assume liability for damage or loss arising from use of third-party services accessed via links on Al-Andalus Translate, unless mandatory law provides otherwise.",
      "If you find a broken, misleading, or unlawful link, you may report it through the contact form so we can assess removal or replacement with reasonable promptness.",
    ],
  },
  {
    heading: "No professional advice",
    paragraphs: [
      "Explanatory texts on the Site (usage guides, FAQs, articles on language integration or general procedures) are for informational and educational purposes. They do not create an attorney–client, doctor–patient, financial adviser–user, or similar relationship, even when they touch topics that in real life often require specialized advice.",
      "Migrant communities and their families in Spain and Latin America often need guidance on nationality, family reunification, benefits, healthcare, or education. That guidance should come from licensed professionals, accredited NGOs, or competent public services. Never make an important decision based solely on an automatic translation of a form, deadline, or legal requirement you read for the first time in our translator.",
      "If the Site mentions agencies or administrative procedures, rules and deadlines may change. Always confirm information against current official sources in a language you understand, or with a qualified interpreter in in-person settings.",
    ],
  },
  {
    heading: "Accuracy of information",
    paragraphs: [
      "We strive to ensure that service descriptions, character limits, usage instructions, and security notices reflect actual Site behavior at the time of publication. Nevertheless, typographical errors, delays in updating after a technical change, or discrepancies between mobile and desktop versions may occur without intent.",
      "Automatic translations do not guarantee semantic, grammatical, or cultural accuracy. They may omit nuances of courtesy in Arabic, confuse homophones in Spanish, incorrectly gender references, or choose an inappropriate register (formal versus colloquial). For technical text (IT, law, medicine, engineering), error rates are typically higher than in everyday conversation.",
      "We do not promise that the Site will be free of interruptions, viruses, or vulnerabilities, although we apply reasonable security measures and development practices. Any exclusive reliance on the Site for critical communications is at your own risk.",
    ],
  },
  {
    heading: "Affiliate programs and advertising",
    paragraphs: [
      "To keep free access to the translator, the Site may display advertising (for example through networks such as Google AdSense or other advertising partners) and, in the future, affiliate links to products or services related to language learning, textbooks, or digital tools. When a commercial relationship could influence our recommendation, we will seek to disclose it clearly in context.",
      "Ads and sponsored links are the responsibility of their respective advertisers. We do not control creative messaging or third-party advertisers' landing pages. Views expressed in our own editorial articles are not sold in exchange for ad placement; separation between informational content and monetization is an editorial principle we apply in good faith.",
      "If you make a purchase through an affiliate link, the Site may earn a commission at no extra cost to you under the merchant's terms. That commission does not change the free core translation function nor imply that we endorse every advertised product.",
    ],
  },
  {
    heading: "Errors and omissions",
    paragraphs: [
      "Despite internal controls, errors or omissions may exist in legal texts, FAQs, metadata, or sample translations shown for illustration. We reserve the right to correct them at any time without an obligation to notify each user individually, unless the law requires specific notice.",
      "If you suffer harm you attribute directly to a material error on the Site (not to the inherent nature of machine translation), you may contact us with the facts and relevant documentation. We will consider each good-faith communication; in any case, the owner's aggregate liability is limited as set out in the Terms and Conditions and mandatory applicable law.",
      "Users and contributors who send suggestions or bug reports help us improve the service; unless otherwise agreed in writing, we do not pay for those submissions nor acquire rights over ideas not protected by intellectual property law.",
    ],
  },
  {
    heading: "Changes to this notice",
    paragraphs: [
      "We may amend this Legal Notice to reflect legislative changes (for example on digital services or data protection), new translator features, or requirements of advertising and analytics platforms. The current version will be the one published at this URL with the update date shown in the header (May 2026).",
      "Continued use of the Site after publication of material changes may be treated as acceptance of the revised text, without prejudice to non-waivable rights under Spanish and European law. Where changes materially affect personal data processing, we will refer you to the Privacy Policy and, when required, to consent mechanisms provided by law.",
    ],
  },
  {
    heading: "Contact",
    paragraphs: [
      "For questions about this Legal Notice, to report defective links, or to ask about the scope of machine translation versus professional services, write to us using the contact form on the Site (route /contact). Use the subject line \"Legal notice\" to help us classify your message.",
      "We will respond within a reasonable time. English is the primary language of this notice and of project management correspondence; Spanish and Arabic-speaking users in Spain and Latin America are welcome to write in any of those languages. You may use our translator as orientational support to understand this document, but for situations with legal consequences we recommend bilingual human assistance or sworn translation of any text you must submit to authorities.",
    ],
  },
];
